version: 2.1
executors:
  python:
    docker:
      - image: circleci/python:3.6
commands:
  version_check:
    steps:
      - run: python -V
jobs:
  plan:
    executor: python
#     docker:
#       - image: circleci/python:3.6
    steps:
      - checkout
      - version_check
#       - run: |
#           python -V
#   aws:
#     docker:
#       - image: mesosphere/aws-cli
#     steps:
#       - run: |
#           which aws
workflows:
#   version: 2.1
  build:
    jobs:
      - plan
#       - aws
