version: 2
jobs:
  plan:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          cat README.md
  aws:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - run: |
          which aws
workflows:
  version: 2
  build:
    jobs:
      - plan
      - aws
