version: 2.1
jobs:
  plan:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python -V
      - run: |
          echo $TEST_KEY
#   aws:
#     docker:
#       - image: mesosphere/aws-cli
#     steps:
#       - run: |
#           which aws
workflows:
  version: 2.1
  build:
    jobs:
      - plan
#       - aws
