version: 2.1
executors:
  python:
    docker:
      - image: circleci/python:3.6
  plan:
#     docker:
#       - image: circleci/python:3.6
    executor:
      name: python
    steps:
      - checkout
      - run: |
          python -V
#   aws:
#     docker:
#       - image: mesosphere/aws-cli
#     steps:
#       - run: |
#           which aws
workflows:
  version: 2.1
  build:
    jobs:
      - plan
#       - aws
